// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace wr.entity
{
    public partial class Branch
    {
        public Branch()
        {
            User = new HashSet<User>();
        }

        public int BranchId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public int? BranchHeadId { get; set; }
        public DateTime? OpeningDate { get; set; }
        public DateTime? DeactiveDate { get; set; }
        public bool? IsActive { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedTime { get; set; }

        public virtual ICollection<User> User { get; set; }
    }
}