// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace wr.entity
{
    public partial class Theme
    {
        public int ThemeId { get; set; }
        public int? Uid { get; set; }
        public int? ColorId { get; set; }
        public int? Createdby { get; set; }
        public DateTime? Createdtime { get; set; }

        public virtual Color Color { get; set; }
        public virtual User U { get; set; }
    }
}